main: de.craftlancer.imagemaps.ImageMaps
author: SydMontague
version: ${project.version}
name: ImageMaps
commands:
    imagemap:
        usage: |
          /imagemap <file/url> <fastsend> - then rightlick on a block, fastsend is either true or false
          /imagemap <file> reload - reloads the imagefile
        permission: imagemaps.use
permissions:
    imagemaps.use:
        default: op
    